name: 'Certum code signing'
description: |
  Code signs Windows binaries using Certum service Code Sign in the Cloud.
  Env variables CERTUM_EMAIL and CERTUM_OTP are expected to be set.
author: 'Andy Gajdosik'
branding:
  icon:  shield
  color: blue

inputs:
  input_path:
    description: 'Path to file or directory to sign'
    deault: '*.exe'
    required: true

  certum_email:
    description: 'Certum account e-mail'

  ssign_version:
    description: 'Version of the ssign tool to use (https://docs.rs/crate/ssign)'
    default: '0.28.0'

outputs:
  output_path:
    description: 'Path to signed/notarized/stapled entity'

runs:
  using: "composite"
  steps:
    - name: Install Cargo
      shell: sh
      run: cargo install ssign
    - name: Code sign the binaries
      shell: sh
      env:
        INPUT_PATH: ${{ inputs.input_path }}
      run: ssign $INPUT_PATH
