name: 'Certum code signing'
description: |
  Code signs Windows binaries using Certum service Code Sign in the Cloud.
  Env variables CERTUM_EMAIL and CERTUM_OTP are expected to be set.
author: 'Andy Gajdosik'
branding:
  icon:  shield
  color: blue

inputs:
  input_path:
    description: 'Path to file or directory to sign. Wildcard * can be used.'
    deault: '*.exe'
    required: true

  certum_email:
    description: 'Certum account e-mail'

  ssign_version:
    description: 'Version of the ssign tool to use (https://docs.rs/crate/ssign).'
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install ssign (latest)
      if: ${{ inputs.ssign_version == '' }}
      shell: sh
      run: cargo install ssign

    - name: Install ssign ${{ inputs.ssign_version }} 
      if: ${{ inputs.ssign_version != '' }}
      shell: sh
      run: cargo install ssign --version ${{ inputs.ssign_version }}

    - name: Code sign the binaries
      shell: sh
      env:
        INPUT_PATH: ${{ inputs.input_path }}
      run: ssign $INPUT_PATH
